services:
  app:
    image: gabrielschiestl/authgate:latest
    ports:
      - "50051:50051"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - authgate-network

networks:
  authgate-network:
    driver: bridge
